<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="146" started-at="2020-08-26T16:28:14Z" finished-at="2020-08-26T16:28:14Z">
    <groups>
      <group name="signIn">
        <method signature="TestNg.fbsignIn()[pri:0, instance:testcases.TestNg@42d80b78]" name="fbsignIn" class="testcases.TestNg"/>
        <method signature="TestNg.signIn()[pri:0, instance:testcases.TestNg@42d80b78]" name="signIn" class="testcases.TestNg"/>
      </group> <!-- signIn -->
    </groups>
    <test name="Default test" duration-ms="146" started-at="2020-08-26T16:28:14Z" finished-at="2020-08-26T16:28:14Z">
      <class name="testcases.TestNg">
        <test-method status="FAIL" signature="fbsignIn()[pri:0, instance:testcases.TestNg@42d80b78]" name="fbsignIn" duration-ms="44" started-at="2020-08-26T21:58:14Z" finished-at="2020-08-26T21:58:14Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
	at testcases.TestNg.fbsignIn(TestNg.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fbsignIn -->
        <test-method status="PASS" signature="signIn()[pri:0, instance:testcases.TestNg@42d80b78]" name="signIn" duration-ms="4" started-at="2020-08-26T21:58:14Z" finished-at="2020-08-26T21:58:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signIn -->
        <test-method status="SKIP" signature="viewAcc()[pri:0, instance:testcases.TestNg@42d80b78]" name="viewAcc" duration-ms="0" depends-on-groups="signIn" started-at="2020-08-26T21:58:14Z" finished-at="2020-08-26T21:58:14Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestNg.viewAcc()[pri:0, instance:testcases.TestNg@42d80b78] depends on not successfully finished methods in group "signIn"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestNg.viewAcc()[pri:0, instance:testcases.TestNg@42d80b78] depends on not successfully finished methods in group "signIn"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- viewAcc -->
      </class> <!-- testcases.TestNg -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
